/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as TripsTripIdJoinRouteImport } from './routes/trips.$tripId.join'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdJoinRoute = TripsTripIdJoinRouteImport.update({
  id: '/$tripId/join',
  path: '/$tripId/join',
  getParentRoute: () => TripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/itinerary': typeof ItineraryRoute
  '/journal': typeof JournalRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRouteWithChildren
  '/api/transcribe': typeof ApiTranscribeRoute
  '/shared/$token': typeof SharedTokenRoute
  '/trips/$tripId/join': typeof TripsTripIdJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/itinerary': typeof ItineraryRoute
  '/journal': typeof JournalRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRouteWithChildren
  '/api/transcribe': typeof ApiTranscribeRoute
  '/shared/$token': typeof SharedTokenRoute
  '/trips/$tripId/join': typeof TripsTripIdJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/itinerary': typeof ItineraryRoute
  '/journal': typeof JournalRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/trips': typeof TripsRouteWithChildren
  '/api/transcribe': typeof ApiTranscribeRoute
  '/shared/$token': typeof SharedTokenRoute
  '/trips/$tripId/join': typeof TripsTripIdJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/itinerary'
    | '/journal'
    | '/planner'
    | '/profile'
    | '/saved'
    | '/trips'
    | '/api/transcribe'
    | '/shared/$token'
    | '/trips/$tripId/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/itinerary'
    | '/journal'
    | '/planner'
    | '/profile'
    | '/saved'
    | '/trips'
    | '/api/transcribe'
    | '/shared/$token'
    | '/trips/$tripId/join'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/itinerary'
    | '/journal'
    | '/planner'
    | '/profile'
    | '/saved'
    | '/trips'
    | '/api/transcribe'
    | '/shared/$token'
    | '/trips/$tripId/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  ItineraryRoute: typeof ItineraryRoute
  JournalRoute: typeof JournalRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  TripsRoute: typeof TripsRouteWithChildren
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/join': {
      id: '/trips/$tripId/join'
      path: '/$tripId/join'
      fullPath: '/trips/$tripId/join'
      preLoaderRoute: typeof TripsTripIdJoinRouteImport
      parentRoute: typeof TripsRoute
    }
  }
}

interface TripsRouteChildren {
  TripsTripIdJoinRoute: typeof TripsTripIdJoinRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsTripIdJoinRoute: TripsTripIdJoinRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  ItineraryRoute: ItineraryRoute,
  JournalRoute: JournalRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  TripsRoute: TripsRouteWithChildren,
  ApiTranscribeRoute: ApiTranscribeRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
